# Generated by Django 3.0.6 on 2020-05-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('category', models.CharField(max_length=60, verbose_name='Category')),
                ('blog_date', models.DateTimeField(verbose_name='Date')),
                ('blog_content', models.TextField(verbose_name='Contents')),
            ],
        ),
    ]
