# Generated by Django 3.0.6 on 2020-05-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_blogslist_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogslist',
            name='blog_img',
            field=models.ImageField(upload_to='blogs/', verbose_name='Image'),
        ),
    ]
